print("Первый этап:")
step1 = input()
print("Второй этап:")
step2 = input()
print("Третий этап:")
step3 = input()
print("Четвертый этап:")
step4 = input()
print("Пятый этап:")
step5 = input()
print(step1, step2, step3, step4, step5, sep="=>")